events {}

http {
    upstream user_service {
        server user-service:3000;
    }

    upstream event_service {
        server event-service:3000;
    }

    upstream ticket_service {
        server ticket-service:3000;
    }

    upstream payment_service {
        server payment-service:3000;
    }

    upstream notification_service {
        server notification-service:3000;
    }


    server {
        listen 80;
        server_name localhost;

        location /api/users/ {
            proxy_pass http://user_service/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/events/ {
            proxy_pass http://event_service/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/tickets/ {
            proxy_pass http://ticket_service/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/payments/ {
            proxy_pass http://payment_service/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/notifications/ {
            proxy_pass http://notification_service/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }


        location /api/docs/users/ {
            proxy_pass http://user_service/api/docs/;
        }

        location /api/docs/events/ {
            proxy_pass http://event_service/api/docs/;
        }

        location /api/docs/tickets/ {
            proxy_pass http://ticket_service/api/docs/;
        }

        location /api/docs/payments/ {
            proxy_pass http://payment_service/api/docs/;
        }

        location /api/docs/notifications/ {
            proxy_pass http://notification_service/api/docs/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }


        location = /api/health/user {
            proxy_pass http://user_service/health;
        }

        location = /api/health/event {
            proxy_pass http://event_service/health;
        }

        location = /api/health/ticket {
            proxy_pass http://ticket_service/health;
        }

        location = /api/health/payment {
            proxy_pass http://payment_service/health;
        }

        location = /api/health/notification {
            proxy_pass http://notification_service/health;
        }


        location = /api/db-check/user {
            proxy_pass http://user_service/db-check;
        }

        location = /api/db-check/event {
            proxy_pass http://event_service/db-check;
        }

        location = /api/db-check/ticket {
            proxy_pass http://ticket_service/db-check;
        }

        location = /api/db-check/payment {
            proxy_pass http://payment_service/db-check;
        }

        location = /api/db-check/notification {
            proxy_pass http://notification_service/db-check;
        }

    }
}
