services:
  user-service:
    build:
      context: ./services/user-service
    container_name: user-service
    ports:
      - "3001:3001"
    env_file:
      - ./services/user-service/.env
    networks:
      - ems-network

  event-service:
    build:
      context: ./services/event-service
    container_name: event-service
    ports:
      - "3002:3002"
    env_file:
      - ./services/event-service/.env
    networks:
      - ems-network

  ticket-service:
    build:
      context: ./services/ticket-service
    container_name: ticket-service
    ports:
      - "3003:3003"
    env_file:
      - ./services/ticket-service/.env
    networks:
      - ems-network
    depends_on:
      - event-service
      - payment-service
      - notification-service

  payment-service:
    build:
      context: ./services/payment-service
    container_name: payment-service
    ports:
      - "3004:3004"
    env_file:
      - ./services/payment-service/.env
    networks:
      - ems-network
    depends_on:
      - notification-service

  notification-service:
    build:
      context: ./services/notification-service
    container_name: notification-service
    ports:
      - "3005:3005"
    env_file:
      - ./services/notification-service/.env
    networks:
      - ems-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - event-service
      - ticket-service
      - payment-service
      - notification-service
    networks:
      - ems-network

networks:
  ems-network:
    driver: bridge
